# Generated by Django 2.2.2 on 2019-06-29 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomName', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('active', models.IntegerField(default=0)),
                ('createdAt', models.DateField()),
            ],
        ),
    ]
