# Generated by Django 2.2.2 on 2019-06-29 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserParticapation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userUsername', models.IntegerField()),
                ('traderId', models.IntegerField()),
                ('roomId', models.IntegerField()),
                ('investment', models.DecimalField(decimal_places=2, default=0.0, max_digits=13)),
            ],
        ),
    ]
