# Generated by Django 2.2.2 on 2019-06-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userParticipation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userparticapation',
            name='userUsername',
            field=models.TextField(),
        ),
    ]
