# Generated by Django 2.2.1 on 2019-06-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userParticipation', '0002_auto_20190629_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='userparticapation',
            name='strategyId',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userparticapation',
            name='roomId',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userparticapation',
            name='traderId',
            field=models.CharField(max_length=255),
        ),
    ]
