# Generated by Django 2.2.1 on 2019-06-29 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradingSession', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingsession',
            name='userSelectedTraderId',
        ),
    ]
