# Generated by Django 2.2.1 on 2019-06-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traderParticipation', '0002_auto_20190629_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderparticapation',
            name='traderName',
            field=models.CharField(default='Trader X', max_length=255),
        ),
    ]
